name: test-git-migration
on:
  push:
    branches:
      - main
      - feature
      - release

jobs:
    build:
      runs-on: ubuntu-latest

      steps:

        - name: Checking branch
          run: |
            if [[ "${GITHUB_REF}" == refs/heads/main ]]; then
                echo "The push has been done from main branch"
            elif [[ "${GITHUB_REF}" == "refs/heads/feature" ]]; then
                echo "The push has been done from feature branch"
            elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
                echo "The push has been done from release branch"
            else
                exit 1
            fi
