name: test-git-migration
on:
  push:
    branches:
      - main
      - feature
      - release

jobs:
    build-main:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
      steps:
        - name: main branch
          run: |
            echo "The push has been done from main branch"
   


    build-feature:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/feature'
      steps:
        - name: feature branch
          run: |
            echo "The push has been done from feature branch"



    build-release:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/release'
      steps:
        - name: release branch
          run: |
            echo "The push has been done from release branch"
